#+title: Readme

Контейнеризация разработки на bash и docker в vscode [[https://containers.dev/][devcontainer]]-совместимом виде.

* Что умеет
1. Работа на стандартных инструментах - bash, Docker, Docker Compose, без магии. Можно использовать без vscode и в ci/cd.
2. Не нужны никакие дополнительные пакеты для работы
3. Быстрая контейнеризация любого проекта и любой активности: не надо вспоминать мелкие настройки, править gitignore, dockerignore, как хранить историю bash и т.д.
4. Можно отлаживать создание devcontainer
5. Кэш при сборке, хранение истории bash
6. Поддержка features
7. self-contained repository: для работы и запуска не нужны репозитории features 

* Использование
** Инициализация devcontainer
#+begin_src shell
git clone https://github.com/vasily-fedorov/devcontainer
cd project
../devcontainer/init <project_name>
#+end_src

** Использование devcontainer
В корне проекта:
#+begin_src shell
.devcontainer/activate
#+end_src
И попадаем в =bash= внутри контейнера.
Редактировать исходный код можно снаружи контейнера, можно внутри. Внутри контейнера он расположен в =/workspace=.

** Подключение features
Можно подключать локальные features в devcontainer-совместимом виде.

Для подключения оформленного по стандарту devcontainer feature используется команда feature:
#+begin_src shell
feature add <path_to_feature>
#+end_src

Например, в корне проекта:
#+begin_src shell
../devcontainer/feature add ../devcontainer/features/python
#+end_src

** Доступные команды
Доступные после инициализации команды повторяют devcontainer/cli .
- .devcontainer/up :: сборка и запуск контейнеров
- .devcontainer/build :: сборка контейнеров
- .devcontainer/activate :: сборка, запуск и логин в bash внутри основного контейнера
- .devcontainer/exec :: запуск команды внутри контейнера. Например,  =/devcontainer/exec bash= запускает в shell внутри контейнера.
- .devcontainer/stop :: останавливает контейнеры
- .devcontainer/down :: останавливает контейнеры

** Удаление features
#+begin_src shell
../devcontainer/feature delete <feature_name>
#+end_src

** Данные, кэш и bash_history
Все данные по умолчанию внутри ./.devcontainer
- .devcontainer/bash_history :: история bash внутри контейнера
- .devcontainer/data :: данные подключенных сервисов
- .devcontainer/cache :: ~/.cache

* Что сделано
** Кэширование apt и pip
При сборке необходимые пакеты скачиваются один раз, в следующий раз сборка пройдет быстрее.
** Ведение истории bash
** Правильные gitignore и dockerignore
** Поддержка devcontainer features
- Локальные features с установкой через install.sh
- Поддержка compose.yaml для features

* Пример использования
#+begin_src shell
$ git clone https://github.com/django-ve/django-helloworld
$ git clone https://github.com/vasily-fedorov/devcontainer
$ git clone https://github.com/devcontainers/features.git
$ cd django-helloworld
$ ../devcontainer/init --port=8643 helloworld
$ ../devcontainer/feature add ../features/src/python
$ .devcontainer/activate
helloworld@:/workspace$ pip install -r requirements.txt
helloworld@:/workspace$ python manage.py migrate
helloworld@:/workspace$ python manage.py runserver 0.0.0.0:8643 &
helloworld@:/workspace$ curl http://localhost:8643
Hello, world!
Ctrl-D
$ curl http://localhost:8643
Hello, world!
#+end_src
То есть можем работать в окружении внутри контейнера, а можем редактировать код в привычном редакторе снаружи и смотреть внутрь контейнера через указанный порт.


* Тестирование
Для запуска всех тестов:
#+begin_src bash
make test
#+end_src

* Структура проекта
#+begin_src
devcontainer/
├── devcontainer/       # Шаблоны для инициализации стороннего проекта
│   ├── Dockerfile
│   ├── compose.yaml
│   ├── devcontainer.json
│   ├── up
│   ├── stop
│   ├── down
│   ├── activate
│   ├── exec
│   └── ...
├── feature             # Скрипт управления features
├── init               # Скрипт инициализации проекта
├── test/              # Тесты
│   ├── feature-python.sh
│   ├── devcontainer-features-python.sh
│   └── devcontainers-cli-compat.sh
├── Makefile           # Управление тестированием
└── README.org
#+end_src
