services:
  minio:
    container_name: minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/minio:/data
