services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: djpassword
      POSTGRES_USER: djuser
      POSTGRES_DB: memonik
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
